//Referencing DOM elements

const fname = document.getElementById("firstName")
const lname = document.getElementById("lastName")
const email = document.getElementById("email")
const phoneNumber = document.getElementById("phoneNumber")
const country = document.getElementById("country")
const checkin = document.getElementById("checkin")
const checkout = document.getElementById("checkout")
const noAdults = document.getElementById("noAdults")
const noChildren = document.getElementById("noChildren")
const noRooms = document.getElementById("noRooms")
const single = document.getElementById("single")
const double = document.getElementById("double")
const triple = document.getElementById("triple")
const wifi = document.getElementById("wifi")
const pool = document.getElementById("pool")
const garden = document.getElementById("garden")
const advNone = document.getElementById("advNone")
const advSky = document.getElementById("advSky")
const advCul = document.getElementById("advCul")
const advSurf = document.getElementById("advSurf")
const advSea = document.getElementById("advSea")
const promocode = document.getElementById("promocode")
const loyalpoints = document.getElementById("loyalpoints")
const advBook = document.getElementById("book_adv_btn")
const book = document.getElementById("book_btn")